from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideVendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("vehicle_number", models.CharField(blank=True, default="",
                                                   max_length=24)),
                ("vehicle_model", models.CharField(blank=True, default="",
                                                  max_length=80)),
                ("auto_active", models.BooleanField(default=True)),
                ("auto_base", models.DecimalField(decimal_places=2, default=25.0,
                                                  max_digits=8)),
                ("auto_per_km", models.DecimalField(decimal_places=2, default=12.0,
                                                   max_digits=8)),
                ("mini_active", models.BooleanField(default=True)),
                ("mini_base", models.DecimalField(decimal_places=2, default=30.0,
                                                  max_digits=8)),
                ("mini_per_km", models.DecimalField(decimal_places=2, default=14.0,
                                                   max_digits=8)),
                ("sedan_active", models.BooleanField(default=False)),
                ("sedan_base", models.DecimalField(decimal_places=2, default=45.0,
                                                   max_digits=8)),
                ("sedan_per_km", models.DecimalField(decimal_places=2, default=18.0,
                                                    max_digits=8)),
                ("xl_active", models.BooleanField(default=False)),
                ("xl_base", models.DecimalField(decimal_places=2, default=60.0,
                                                max_digits=8)),
                ("xl_per_km", models.DecimalField(decimal_places=2, default=23.0,
                                                 max_digits=8)),
                ("is_online", models.BooleanField(default=False)),
                ("total_rides", models.PositiveIntegerField(default=0)),
                ("total_earnings", models.DecimalField(decimal_places=2,
                                                       default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor", models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="ride_profile", to="myapp.vendorprofile")),
            ],
            options={
                "verbose_name": "Ride partner",
                "verbose_name_plural": "Ride partners",
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("ride_code", models.CharField(editable=False, max_length=20,
                                               unique=True)),
                ("vehicle_type", models.CharField(default="auto", max_length=16)),
                ("pickup_text", models.CharField(max_length=200)),
                ("pickup_lat", models.FloatField(blank=True, null=True)),
                ("pickup_lng", models.FloatField(blank=True, null=True)),
                ("drop_text", models.CharField(max_length=200)),
                ("drop_lat", models.FloatField(blank=True, null=True)),
                ("drop_lng", models.FloatField(blank=True, null=True)),
                ("distance_km", models.FloatField(default=0.0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("base_fare", models.DecimalField(decimal_places=2, default=0,
                                                  max_digits=8)),
                ("per_km", models.DecimalField(decimal_places=2, default=0,
                                              max_digits=8)),
                ("fare", models.DecimalField(decimal_places=2, default=0,
                                             max_digits=10)),
                ("split_fee", models.DecimalField(decimal_places=2, default=0,
                                                  max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=0,
                                              max_digits=10)),
                ("payment_mode", models.CharField(
                    blank=True, default="", max_length=10,
                    choices=[("full", "Full payment"),
                             ("split", "50-50 split (+5%)")])),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0,
                                                    max_digits=10)),
                ("balance_due", models.DecimalField(decimal_places=2, default=0,
                                                    max_digits=10)),
                ("txn_first", models.CharField(blank=True, default="",
                                               max_length=120)),
                ("txn_second", models.CharField(blank=True, default="",
                                                max_length=120)),
                ("payment_done", models.BooleanField(default=False)),
                ("otp", models.CharField(blank=True, default="", max_length=6)),
                ("status", models.CharField(
                    db_index=True, default="requested", max_length=16,
                    choices=[("requested", "Requested"),
                             ("accepted", "Accepted"),
                             ("paid", "Paid"),
                             ("arrived", "Arrived"),
                             ("ongoing", "Ongoing"),
                             ("completed", "Completed"),
                             ("rejected", "Rejected"),
                             ("cancelled", "Cancelled")])),
                ("cancel_reason", models.CharField(blank=True, default="",
                                                   max_length=200)),
                ("student_name", models.CharField(blank=True, default="",
                                                  max_length=120)),
                ("student_phone", models.CharField(blank=True, default="",
                                                   max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rider", models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            related_name="rides", to="ride.ridevendor")),
                ("student", models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              related_name="rides",
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
