# Generated by Django 6.1.1 on 2026-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_ridepax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderblock',
            name='end_min',
            field=models.IntegerField(default=1439, help_text='minutes past midnight'),
        ),
        migrations.AlterField(
            model_name='riderblock',
            name='start_min',
            field=models.IntegerField(default=0, help_text='minutes past midnight'),
        ),
        migrations.AlterField(
            model_name='riderblock',
            name='weekday',
            field=models.IntegerField(default=0, help_text='0 = Monday … 6 = Sunday'),
        ),
    ]
