# Generated by Django 6.1.1 on 2026-09-16 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_feed_v49'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DisabledAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(default='🛍', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrafficStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('impressions', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.CharField(default='food', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disabledaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_flag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyvisit',
            index=models.Index(fields=['date'], name='myapp_daily_date_582895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyvisit',
            unique_together={('date', 'user')},
        ),
    ]
