# Generated by Django 6.1.1 on 2026-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_fooditem_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='offer_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('bogo', 'Buy 1 Get 1 Free'), ('addon', 'Free Add-on')], default='percentage', max_length=12),
        ),
    ]
